### ISSUE TITLE
issue running discovery server

### ISSUE THREAD

**Issue by pghdeveloper** [alejandro-du/vaadin-microservices-demo#3]
Hi Alejandro,

I downloaded your microservices application.  I have java and Maven.  When I try to run java -jar target/discovery-server-0.0.1-SNAPSHOT.jar  in the command window(I'm using Windows 8.1), I'm getting an error:  java.lang.TypeNotPresentException: Type javax.xml.bind.JAXBContext not present

I tried putting in 

<dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.0</version>
    </dependency

in the pom.xml file but still getting the same error.

Have you seen this before?

Randy

**Comment by pghdeveloper** [comment]
I was able to resolve the issue by using java 9.0.4 for Maven.  However when I try to run biz-application, I get an error:

 nested exception is org.springframework.beans.factory.BeanCreationException: Er
ror creating bean with name 'entityManagerFactory' defined in class path resourc
e [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.clas
s]: Invocation of init method failed; nested exception is java.lang.NoClassDefFo
undError: javax/xml/bind/JAXBException

**Comment by alejandro-du** [comment]
A bit late, but here I go: Thanks for reporting and sharing the solution. Cheers!
