### ISSUE TITLE
Delete in CrudView does not work.

### ISSUE THREAD

**Issue by unixhelden** [alejandro-du/vaadin-microservices-demo#4]
Hi alejandro. In biz-application you have named your ID Variable as "id", it should be "Id" else it won't get translated into the output Json. Hence crudview does not delete anything because it doesn't know about the ID.

https://stackoverflow.com/questions/30912826/expose-all-ids-when-using-spring-data-rest/38938767#38938767

**Comment by alejandro-du** [comment]
It actually works thanks to this: https://github.com/alejandro-du/vaadin-microservices-demo/blob/master/biz-application/src/main/java/com/example/biz/BizApplication.java#L21
