### ISSUE TITLE
org.vaadin.crudui.crudui 4.3.2 not available ?

### ISSUE THREAD

**Issue by 2portusbswitch** [alejandro-du/vaadin-microservices-demo#5]
in vaadin-microservices-demo/admin-application/pom.xml
org.vaadin.crudui.crudui  request 4.3.2-SNAPSHOT

Only 4.3.1 seems available and running with 4.3.1 throw a "Caused by: java.io.NotSerializableException: org.vaadin.crudui.form.AbstractAutoGeneratedCrudFormFactory$$Lambda$1486/0x0000000800daa040"

**Comment by alejandro-du** [comment]
You are right. Crud-UI 4.3.2 is available now. I forgot to publish the version and remove the SNAPSHOT in this project. All fixed now. Thanks for reporting the issue.
