### ISSUE TITLE
How to use PreserveOnRefresh

### ISSUE THREAD

**Issue by rob-64** [alejandro-du/vaadin-microservices-demo#8]
I was wondering if you know how to use PreserveOnRefresh with the demo? Seems like Spring session is breaking it?

**Comment by sombochea** [comment]
I can't using Push too.

**Comment by rob-64** [comment]
Way late response, but the issue ended up being NavigationEvent is getting serialized and the source is being lost..

if u override the class:

`  
@Override
  public Router getSource() {
    Router source = (Router) super.getSource();
    if (source == null) {
      source = VaadinService.getCurrent().getRouter();
    }
    return source;
  }
`

**Comment by alejandro-du** [comment]
Thanks for sharing the solution!
